"""Build the static report site.

Generates a real report for each demo target and an index that links them. The
HTML renderer already emits self-contained pages with no external requests, so
the output is a directory of static files and nothing else -- no build step, no
runtime, no server.

Usage:
    uv run python scripts/build_site.py site
"""

from __future__ import annotations

import sys
import tempfile
from html import escape
from pathlib import Path

from agent_trust.models import Report
from agent_trust.pipeline import audit
from agent_trust.render import render_html

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_fixtures import build_clean, build_ugly  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

INDEX_CSS = """
:root { --bg:#fbfaf8; --fg:#1c1b19; --muted:#6b6862; --line:#e2ddd5; --card:#fff;
        --a:#1f7a4d; --b:#4f7a1f; --c:#9a7a12; --d:#a85a12; --f:#a8261a; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#16151a; --fg:#eceaf3; --muted:#a09caa; --line:#2e2c36; --card:#1e1d24;
          --a:#5fd39b; --b:#a8d35f; --c:#e0c05a; --d:#e39a5a; --f:#f0776a; } }
* { box-sizing:border-box; }
body { margin:0; padding:3rem 1.25rem 5rem; background:var(--bg); color:var(--fg);
  font:16px/1.65 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; }
main { max-width:52rem; margin:0 auto; }
h1 { font-size:1.75rem; margin:0 0 .5rem; letter-spacing:-.02em; }
.lede { color:var(--muted); margin:0 0 2.5rem; font-size:1.05rem; }
a.card { display:block; text-decoration:none; color:inherit; background:var(--card);
  border:1px solid var(--line); border-radius:.6rem; padding:1.1rem 1.3rem; margin:.75rem 0; }
a.card:hover { border-color:var(--muted); }
.row { display:flex; align-items:baseline; gap:.9rem; }
.grade { font-size:2rem; font-weight:700; line-height:1; letter-spacing:-.03em; }
.A{color:var(--a)}.B{color:var(--b)}.C{color:var(--c)}.D{color:var(--d)}.F{color:var(--f)}
.name { font-weight:600; }
.note { color:var(--muted); font-size:.9rem; margin:.4rem 0 0; }
code { font-family:ui-monospace,Menlo,Consolas,monospace; font-size:.85em; }
footer { margin-top:3rem; padding-top:1.25rem; border-top:1px solid var(--line);
  color:var(--muted); font-size:.85rem; }
"""


def index(entries: list[tuple[str, str, Report, str]]) -> str:
    """The landing page linking every generated report."""
    cards = []
    for slug, title, report, note in entries:
        letter = report.overall.letter.value
        score = "N/A" if report.overall.score is None else str(report.overall.score)
        cards.append(
            f'<a class="card" href="{slug}.html">'
            f'<div class="row"><span class="grade {letter}">{letter}</span>'
            f'<span class="name">{escape(title)}</span>'
            f'<span class="note">{score}/100</span></div>'
            f'<p class="note">{escape(note)}</p></a>'
        )

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agent Trust Score — reports</title>
<style>{INDEX_CSS}</style></head>
<body><main>
<h1>Agent Trust Score</h1>
<p class="lede">How safely can an autonomous coding agent operate inside this
repository? Five axes, 37 checks, evidence with file and line, and a fix list
ranked by points recovered per hour. These are real reports, generated by the
tool.</p>
{"".join(cards)}
<footer>
Run it yourself: <code>uvx agent-trust-score &lt;repo&gt;</code> ·
<a href="https://github.com/user2922/agent-trust-score">source on GitHub</a><br>
This grades repository structure. It is not a security audit and it certifies
nothing.
</footer>
</main></body></html>
"""


def main() -> int:
    destination = Path(sys.argv[1] if len(sys.argv) > 1 else "site").resolve()
    destination.mkdir(parents=True, exist_ok=True)

    entries: list[tuple[str, str, Report, str]] = []
    with tempfile.TemporaryDirectory() as tmp:
        targets = [
            (
                "clean",
                "A well-prepared repository",
                build_clean(Path(tmp)),
                "The fixture that shows what good looks like: an agent doc, a schema, "
                "guarded destructive operations, CI that actually runs the tests.",
            ),
            (
                "ugly",
                "A repository an agent should not touch",
                build_ugly(Path(tmp)),
                "A committed credential caps the grade on its own. Findings on every "
                "axis, each with the file and line that produced it.",
            ),
            (
                "self",
                "agent-trust-score itself",
                REPO_ROOT,
                "The tool graded by the tool. Its remaining findings are real and "
                "unfixed rather than hidden.",
            ),
        ]
        for slug, title, root, note in targets:
            report = audit(str(root), use_llm=False, use_cache=False, timeout=180)
            (destination / f"{slug}.html").write_text(
                render_html(report), encoding="utf-8", newline=""
            )
            entries.append((slug, title, report, note))
            score = "N/A" if report.overall.score is None else report.overall.score
            print(f"  {slug:<6} {report.overall.letter.value}  {score}")

    (destination / "index.html").write_text(index(entries), encoding="utf-8", newline="")
    print(f"wrote {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
